### ISSUE TITLE
Error "UVC header is not available" while launching

### ISSUE THREAD

**Issue by IoannisKaragiannis** [chutsu/rs4se#3]
Hi Chris,

I have successfully managed to install realsenselib, and I can store imu data in rosbags. However while analyzing the data I realized that the implemented lerp method they have, namely imu_unite_method:="linear_interpolation", is not reliable. That is how I ended up to your repo and I was hoping you could give me a hint why I get the following error. Btw before launching your files I first did a "catkin_make clean", and then "catkin_make -DCATKIN_ENABLE_TESTING=False -DCMAKE_BUILD_TYPE=Release" and "catkin_make install" respectively. When I run "roslaunch rs4se intel_d435i.launch" on my terminal I get the following error.

```
started roslaunch server http://elxc3600002:42557/

SUMMARY
========

PARAMETERS
 * /rosdistro: melodic
 * /rosversion: 1.14.3
 * /stereo/camera0/image/disable_pub_plugins: ['image_transport...
 * /stereo/camera1/image/disable_pub_plugins: ['image_transport...
 * /stereo/enable_emitter: False
 * /stereo/exposure: 10000.0
 * /stereo/format: Y8
 * /stereo/frame_rate: 30
 * /stereo/global_time: True
 * /stereo/height: 480
 * /stereo/sync_size: 30
 * /stereo/width: 640

NODES
  /
    intel_d435i (rs4se/intel_d435i)

auto-starting new master
process[master]: started with pid [18771]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to 0cd0933e-c343-11e9-8d57-7824af85d816
process[rosout-1]: started with pid [18782]
started core service [/rosout]
process[intel_d435i-2]: started with pid [18789]
terminate called after throwing an instance of 'rs2::invalid_value_error'
  what():  UVC header is not available
================================================================================REQUIRED process [intel_d435i-2] has died!
process has died [pid 18789, exit code -6, cmd ~/realsense_original_ws/devel/lib/rs4se/intel_d435i __name:=intel_d435i __log:=~/.ros/log/0cd0933e-c343-11e9-8d57-7824af85d816/intel_d435i-2.log].
log file: ~/.ros/log/0cd0933e-c343-11e9-8d57-7824af85d816/intel_d435i-2*.log
Initiating shutdown!
================================================================================
[intel_d435i-2] killing on exit
[rosout-1] killing on exit
[master] killing on exit
shutting down processing monitor...
... shutting down processing monitor complete
done
```

Do you have any idea what could be the culprit of my problem? Could it be that your pose estimation wrapper depends on some specific release of the RealSense SDK, and that something is messed up with the release I'm trying? Any hint is more than welcome. Thanks in advance for your time.

**Comment by chutsu** [comment]
> That is how I ended up to your repo

Spread the word! :D

Hmm that sounds more like an error on the intel realsense driver side then my code. Namely the UVC header is basically the USB controller that the RealSense uses to poll the image data. If I were you I would double check:

- librealsense version you installed
- check your Intel D435i firmware matches the librealsense version you installed

Additionally:
- What OS are you running?
- How did you install librealsense? compiled from source or via apt?

**Comment by MoBaT** [comment]
You need to install the kernel drivers according to the linrealsense install directions.

**Comment by chutsu** [comment]
Closing due to inactivity.

**Comment by chutsu** [comment]
For future reference:

`rs4se` makes use of [RS2_FRAME_METADATA_FRAME_TIMESTAMP](http://docs.ros.org/kinetic/api/librealsense2/html/rs__frame_8h.html#a91f19a01f5bf2abadc30959a8d3109c9ace5e9a64e51d6c99c5bac8a2dfb56a98) inorder to calculate the image frame's mid-exposure timestamp (see [here](https://github.com/chutsu/rs4se/blob/04221274fed69d4e4ace52d9cd0f4c08a991a4cf/src/common.hpp#L34)). Inorder to obtain that meta-data the linux kernel needs to be patched:

![Screenshot_2019-09-11_16-28-13](https://user-images.githubusercontent.com/91460/64711256-341b1200-d4b1-11e9-89eb-0e3280eb38df.png)

^ screenshot taken from [here](https://github.com/IntelRealSense/librealsense/blob/master/doc/frame_metadata.md#metadata-support-for-intel-realsense-devices).

The linux installation guide ([here](https://github.com/IntelRealSense/librealsense/blob/master/doc/installation.md#prerequisites)) walks through how one would perform this patch.

**Comment by monkeydchopper** [comment]
Nice work! 
I have the same problem here, may I ask the SDK verison you based for the wrapper?

**Comment by chutsu** [comment]
As of 11th September 2019, I have `librealsense 2.28.0` installed

```
[~] > apt-cache policy librealsense2-dev                                                                                                                                                                            
librealsense2-dev:                                                                                                                                                                                                  
  Installed: 2.28.0-0~realsense0.1512                                                                                                                                                                               
  Candidate: 2.28.0-0~realsense0.1512
```
